component: ipaddresses-service

build:
  project_file: src/Roblox.IpAddresses.Service.csproj
  component_directory: ./.deploy

  additional_args:
    - -p:DockerTag=${{ env.NOMAD_VERSION }}

  docker:
    docker_file: Dockerfile
    image_name: docker.artifactory.rbx.com/micro-services/ipaddresses-service
    
deployment:
  count: 3
  namespace: ipaddresses-grpc

  job: ${{ env.NOMAD_ENVIRONMENT }}-roblox-ipaddresses-service

  vault_policies:
    - vault_secret_settings_providers_token_reader

  # Passed to the meta section in Nomad
  meta:
    ENVIRONMENT: ${{ env.NOMAD_ENVIRONMENT }}

  containers: # Maps to the groups section in Nomad
    - image: docker.artifactory.rbx.com/micro-services/ipaddresses-service
      resources:
        cpu: ${{ env.NOMAD_CPU }}
        ram: ${{ env.NOMAD_RAM }}
      network:
        ports:
          grpc: 
            to: 5000
      services:
        - name: ${{ env.NOMAD_ENVIRONMENT }}-ipaddresses-service-grpc
          port: grpc
          tags:
            - ${{ env.NOMAD_ENVIRONMENT }}
            - Roblox.IpAddresses.Service
            - IpAddresses
          checks:
            - type: grpc
              
      volumes:
        - "/etc/ssl/certs:/etc/ssl/certs:ro"
      config_maps:
        - destination: secrets/file.env
          env: true
          on_change: restart
          data: |
            AppName=ipaddresses-service
            DEFAULT_LOG_LEVEL=Information
            VAULT_ADDR="http://vault.service.consul:8200"
            VAULT_TOKEN="{{ with secret "secret/teams/applications/vault-providers" }}{{ .Data.vault_token }}{{ end }}"
